In [2]:
import pandas as pd

df = pd.read_excel("stocks.xlsx", header=[0,1])
df

  Unnamed: 0_level_0    Price                  Price to earnings ratio (P/E)  \
             Company Facebook Google Microsoft                      Facebook
0         2017-06-05      155    955        66                         37.10
1         2017-06-06      150    987        69                         36.98
2         2017-06-07      153    963        62                         36.78
3         2017-06-08      155   1000        61                         36.11
4         2017-06-09      156   1012        66                         37.07


  Google Microsoft
0   32.0     30.31
1   31.3     30.56
2   31.7     30.46
3   31.2     30.11
4   30.0     31.00